/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import dao.ModelManager;
import entity.Model;
import javax.swing.JOptionPane;
import model.ModelActiveComboModel;
import model.ModelActivelListModel;
import renderer.ModelListRenderer;

/**
 *
 * @author boilleau
 */
public class ApplicationModelManagementPanel extends StylePanel {

    /**
     * Creates new form ModelManagementPanel
     */
    private ModelActivelListModel list = new ModelActivelListModel();
    
    public ApplicationModelManagementPanel() {
        initComponents();
    }
    
    /**
     * INUTILE, À SUPPRIMER
     * Crée un modèle d'après les données saisies par l'utilisateur
     */
    public void addModel()
    {
        try
        {
            String name = textName.getText();
            Float diameter = Float.parseFloat(textDiametre.getText() );
            int smallMin = Integer.parseInt(textSmall.getText());
            int middleMin = Integer.parseInt(textMedium.getText());
            int bigMin = Integer.parseInt(textBig.getText());
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Erreur de format d'un des nombres");
        }
    }
    
    
    /**
     * Crée un modèle d'après les données saisies par l'utilisateur
     * @return 
     */
    private Model createModel() throws NumberFormatException
    {
        String name = textName.getText();
        Float diameter = Float.parseFloat(textDiametre.getText() );
        int smallMin = Integer.parseInt(textSmall.getText());
        int middleMin = Integer.parseInt(textMedium.getText());
        int bigMin = Integer.parseInt(textBig.getText());
        Model tmpModel = new Model(name, diameter, smallMin, middleMin, bigMin);
        return tmpModel;
    }
    
    private void resetTextFields()
    {
        this.textBig.setText("");
        this.textDiametre.setText("");
        this.textMedium.setText("");
        this.textName.setText("");
        this.textSmall.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listModel = new javax.swing.JList();
        buttonRemove = new javax.swing.JButton();
        labelNewModel = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelDiametre = new javax.swing.JLabel();
        labelLimit = new javax.swing.JLabel();
        labelSmall = new javax.swing.JLabel();
        labelMedium = new javax.swing.JLabel();
        labelBig = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textDiametre = new javax.swing.JTextField();
        textSmall = new javax.swing.JTextField();
        textMedium = new javax.swing.JTextField();
        textBig = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        labTitlle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonRefresh = new javax.swing.JButton();

        listModel.setModel(list);
        listModel.setCellRenderer(new ModelListRenderer());
        jScrollPane1.setViewportView(listModel);

        buttonRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonRemove.setText("Supprimer");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        labelNewModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNewModel.setText("Nouveau Modèle :");

        labelName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelName.setText("Nom");

        labelDiametre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDiametre.setText("Diamètre");

        labelLimit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelLimit.setText("Seuil par catégorie");

        labelSmall.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSmall.setText("Petit");

        labelMedium.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMedium.setText("Moyen");

        labelBig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBig.setText("Grand");

        buttonOK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonOK.setText("Ajouter modèle");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        labTitlle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitlle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitlle.setText("GESTION DES MODELES");

        buttonRefresh.setText("Rafraîchir");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelNewModel)
                                .addGap(270, 270, 270))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelLimit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelSmall)
                                            .addComponent(labelMedium)
                                            .addComponent(labelBig))
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textSmall, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textMedium, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textBig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(buttonOK))
                                .addGap(267, 267, 267))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(labelName)
                        .addGap(27, 27, 27)
                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDiametre)
                        .addGap(18, 18, 18)
                        .addComponent(textDiametre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labTitlle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labTitlle, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(buttonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(labelNewModel)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelName)
                                .addComponent(labelDiametre)
                                .addComponent(textDiametre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(labelLimit)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSmall)
                            .addComponent(textSmall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMedium)
                            .addComponent(textMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBig)
                            .addComponent(textBig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        try
        {
            if (textName.getText().length() <= 5)
            {
            ((ModelActivelListModel) this.listModel.getModel()).addModel(this.createModel());
            this.resetTextFields();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Le nom du modèle ne doit pas dépasser 5 caractères.", "Erreur dans la saisie du nom", JOptionPane.OK_OPTION, null);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Erreur de format d'un des nombres saisis");
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        ((ModelActivelListModel) this.listModel.getModel()).removeModel((Model) listModel.getSelectedValue());
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        list = new ModelActivelListModel();
        listModel.setModel(list);
    }//GEN-LAST:event_buttonRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labTitlle;
    private javax.swing.JLabel labelBig;
    private javax.swing.JLabel labelDiametre;
    private javax.swing.JLabel labelLimit;
    private javax.swing.JLabel labelMedium;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNewModel;
    private javax.swing.JLabel labelSmall;
    private javax.swing.JList listModel;
    private javax.swing.JTextField textBig;
    private javax.swing.JTextField textDiametre;
    private javax.swing.JTextField textMedium;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textSmall;
    // End of variables declaration//GEN-END:variables
}
