/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import entity.Category;
import entity.Model;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.CategoryComboModel;
import model.ModelComboModel;
import model.StockTableModel;
import renderer.CategoryComboRenderer;
import renderer.ModelComboRenderer;
import view.frame.MainFrame;

/**
 *
 * @author mattar
 */
public class ShopPanel extends StylePanel {

    private MainFrame parent;
    private String logFileName;
    
    public ShopPanel(MainFrame parent) {
        initComponents();
        setVisible(true);
        this.parent = parent;
        
        this.logFileName = "stock_movements.log";
    }
    
    /**
     * Récupère les valeurs entrées par l'utilisateur et met à jour la quantité.
     */
    private void changeStock()
    {
        if (JOptionPane.showConfirmDialog(null,"Confirmez-vous ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
       {
            int quantity = (int) this.crateNumberSpinner.getValue();
            String model = ((Model) this.comboModel.getSelectedItem()).getName();
            String category = ((Category) this.comboCategory.getSelectedItem()).getName();

            ((StockTableModel) this.tabStock.getModel()).changeQuantity(model, category, quantity);  

            // écriture dans l'historique

            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();
            String record = String.format("%s\t%s\t%s\t%d\n", dateFormat.format(date), model, category, quantity);
            
            this.writeHistory(record);
       }
    }
    
    
    private void showHistory()
    {
        FileInputStream fis = null;
        try 
        {
            fis = new FileInputStream(this.logFileName);
        } 
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(ShopPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {  
            ObjectInputStream ois = new ObjectInputStream(fis);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(ShopPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    private void writeHistory(String record)
    {
        BufferedWriter writer = null;
        try {
            //create a temporary file
            File logFile = new File(this.logFileName);

            // This will output the full path where the file will be written to...
            System.out.println(logFile.getCanonicalPath());

            writer = new BufferedWriter(new FileWriter(logFile, true));
            writer.write(record);
          
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        } 
        finally 
        {
            try 
            {
                // Close the writer regardless of what happens...
                writer.close();
            } 
            catch (Exception e) 
            {
                
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitle = new javax.swing.JLabel();
        comboCategory = new javax.swing.JComboBox<Category>();
        buttonOK = new javax.swing.JButton();
        comboModel = new javax.swing.JComboBox<Model>();
        crateNumberSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        buttonHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabStock = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitle.setText("Gestion du Stock");

        comboCategory.setModel(new CategoryComboModel());
        comboCategory.setRenderer(new CategoryComboRenderer());

        buttonOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonOK.setText("Valider");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        comboModel.setModel(new ModelComboModel());
        comboModel.setRenderer(new ModelComboRenderer());
        comboModel.setSelectedItem(new ModelComboModel());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre de Caisses");

        buttonHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonHistory.setText("Historique des Entrées / Sorties");
        buttonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHistoryActionPerformed(evt);
            }
        });

        tabStock.setModel(new model.StockTableModel());
        tabStock.setDefaultRenderer(String.class, new renderer.CrateTableStringRenderer());
        tabStock.setDefaultRenderer(Boolean.class, new renderer.StockTableBooleanRenderer());
        tabStock.setDefaultRenderer(Integer.class, new renderer.StockTableIntegerRenderer());
        jScrollPane1.setViewportView(tabStock);

        tabStock.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer()
            {
                {
                    setOpaque(true);
                }

                @Override
                public Component getTableCellRendererComponent(
                    final JTable table,
                    final Object value,
                    final boolean isSelected,
                    final boolean hasFocus,
                    final int row,
                    final int column)
                {
                    JLabel lab = new JLabel();
                    lab.setOpaque(true);

                    // la font
                    lab.setFont(lab.getFont().deriveFont(Font.BOLD));

                    // centrer le texte
                    lab.setHorizontalAlignment(SwingConstants.CENTER);

                    // le texte à afficher
                    String texte = String.format("%s", value.toString());
                    texte = texte.toUpperCase();

                    lab.setText(texte);
                    lab.setForeground(Color.WHITE);
                    lab.setBackground(Color.GRAY);

                    // renvoie le label
                    return lab;
                }
            });
            jScrollPane1.setViewportView(tabStock);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(comboModel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(crateNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(buttonOK)
                            .addGap(68, 68, 68)
                            .addComponent(buttonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(73, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(crateNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(buttonOK)
                        .addGap(43, 43, 43)
                        .addComponent(buttonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addComponent(labTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(crateNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        this.changeStock(); 
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHistoryActionPerformed
//        ShopHistoryPopUpFrame.getInstance();
        this.showHistory();
    }//GEN-LAST:event_buttonHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHistory;
    private javax.swing.JButton buttonOK;
    private javax.swing.JComboBox<Category> comboCategory;
    private javax.swing.JComboBox<Model> comboModel;
    private javax.swing.JSpinner crateNumberSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labTitle;
    private javax.swing.JTable tabStock;
    // End of variables declaration//GEN-END:variables
}
