/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import view.frame.popup.ShopHistoryPopUpFrame;
import javax.swing.JOptionPane;
import model.CrateTableModel;
import model.ModelComboModel;
import renderer.CrateTableBooleanRenderer;
import renderer.CrateTableIntegerRenderer;
import renderer.CrateTableStringRenderer;
import renderer.ModelComboRenderer;
import view.frame.MainFrame;

/**
 *
 * @author mattar
 */
public class ShopPanel extends StylePanel {

    private MainFrame parent;
    
    public ShopPanel(MainFrame parent) {
        initComponents();
        setVisible(true);
        this.parent = parent;
    }

    
    private void ConfirmAddStock()
    {
        
       if (JOptionPane.showConfirmDialog(null,"Confirmer l'ajout au stock ??", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
       {
           
       }
       else
       {
           
       }
    }
   
    private void ConfirmRemoveStock()
    {
        
       if (JOptionPane.showConfirmDialog(null,"Confirmer le retrait du stock ??", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
       {
           
       }
       else
       {
           
       }


                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboCategory = new javax.swing.JComboBox<String>();
        buttonAddStock = new javax.swing.JButton();
        buttonRemoveStock = new javax.swing.JButton();
        comboModel = new javax.swing.JComboBox<String>();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        buttonHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabStock = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gestion du Stock");

        comboCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categorie", "Petit", "Moyen", "Grand" }));

        buttonAddStock.setText("Ajouter au Stock");
        buttonAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddStockActionPerformed(evt);
            }
        });

        buttonRemoveStock.setText("Retirer du Stock");
        buttonRemoveStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveStockActionPerformed(evt);
            }
        });

        comboModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "modèle", "modele 3", "modele 4", "modele 5", "modele 6", " " }));
        comboModel.setSelectedItem(new ModelComboModel());

        jLabel2.setText("Nombre de Caisses :");

        buttonHistory.setText("Historique des Entrées / Sorties");
        buttonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHistoryActionPerformed(evt);
            }
        });

        tabStock.setModel(new model.CrateTableModel());
        tabStock.setDefaultRenderer(String.class, new renderer.CrateTableStringRenderer());
        tabStock.setDefaultRenderer(Boolean.class, new renderer.CrateTableBooleanRenderer());
        tabStock.setDefaultRenderer(Integer.class, new renderer.CrateTableIntegerRenderer());
        jScrollPane1.setViewportView(tabStock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboModel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(buttonAddStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonRemoveStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRemoveStock, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddStockActionPerformed
        ConfirmAddStock(); 
    }//GEN-LAST:event_buttonAddStockActionPerformed

    private void buttonRemoveStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveStockActionPerformed
        ConfirmRemoveStock();
    }//GEN-LAST:event_buttonRemoveStockActionPerformed

    private void buttonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHistoryActionPerformed
        ShopHistoryPopUpFrame.getInstance();
    }//GEN-LAST:event_buttonHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddStock;
    private javax.swing.JButton buttonHistory;
    private javax.swing.JButton buttonRemoveStock;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable tabStock;
    // End of variables declaration//GEN-END:variables
}
